[2024-02-24 18:18:46,206] [INFO] [server_logger.py:29] Logger initialized
[2024-02-24 18:18:46,244] [ERROR] [login.py:25] Error during connection: Authentication plugin 'caching_sha2_password' is not supported
[2024-02-24 18:18:46,248] [ERROR] [register.py:20] Error during connection: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
[2024-02-24 18:18:46,251] [ERROR] [survey.py:16] Error during connection: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
