[2024-02-26 13:02:13,392] [INFO] [server_logger.py:29] Logger initialized
[2024-02-26 13:02:13,571] [ERROR] [login.py:25] Error during connection: 1049 (42000): Unknown database 'kammarcials'
[2024-02-26 13:02:13,581] [ERROR] [register.py:20] Error during connection: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
[2024-02-26 13:02:13,590] [ERROR] [survey.py:16] Error during connection: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
[2024-02-26 13:04:27,985] [ERROR] [login.py:49] Error in login_model: 'Login' object has no attribute 'cur'
[2024-02-26 13:04:27,986] [INFO] [login_controller.py:17] Login successful
[2024-02-26 13:04:31,614] [ERROR] [login.py:49] Error in login_model: 'Login' object has no attribute 'cur'
[2024-02-26 13:04:31,616] [INFO] [login_controller.py:17] Login successful
[2024-02-26 15:43:17,709] [ERROR] [login.py:49] Error in login_model: 'Login' object has no attribute 'cur'
[2024-02-26 15:43:17,712] [INFO] [login_controller.py:17] Login successful
[2024-02-26 15:43:19,192] [ERROR] [login.py:49] Error in login_model: 'Login' object has no attribute 'cur'
[2024-02-26 15:43:19,193] [INFO] [login_controller.py:17] Login successful
[2024-02-26 15:44:42,722] [ERROR] [login.py:49] Error in login_model: 'Login' object has no attribute 'cur'
[2024-02-26 15:44:42,723] [INFO] [login_controller.py:17] Login successful
[2024-02-26 16:05:24,416] [ERROR] [login.py:49] Error in login_model: 'Login' object has no attribute 'cur'
[2024-02-26 16:05:24,416] [INFO] [login_controller.py:17] Login successful
